### ISSUE TITLE
Docker: Additional property vorta is not allowed

### ISSUE THREAD

**Issue by KeenMaron** [borgbase/vorta-docker#13]
Hi,

i tried to execute the docker compose yaml with "docker-compose up" but i get following error message:

"Additional property vorta is not allowed"

My docker-compose.yml contains:
```
vorta:
    image: ghcr.io/borgbase/vorta-docker:latest
    container_name: vorta
    hostname: storage-vorta
#    cap_add:
#      - SYS_ADMIN
#    security_opt:
#      - apparmor:unconfined
#    privileged: true
    volumes:
      - /volume1/config/vorta:/config
      - /volume1:/data:ro
      - /volumeUSB1/:/destination
    ports:
      - 5811:5800
    restart: unless-stopped
    env_file:
      - ./.env

```
What i'm doing wrong?
